config/routes.rb
Explorer2::Application.routes.draw do
  get "biosearch/index"

scope (Rails.application.config.respond_to?(:relative_url_root) ? Rails.application.config.relative_url_root: '/') do
  root :to => 'home#index'

  match 'favourites' => 'home#index'

  match 'search' => 'home#index'

  match 'compounds' => 'home#index'
  match 'compounds/pharmacology' => 'home#index'
  match 'compounds/structure' => 'home#index'
  match 'compounds/pathways' => 'home#index'
  match 'compounds/draw' => 'home#index'

  match 'targets' => 'home#index'
  match 'targets/pharmacology' => 'home#index'
  match 'targets/pathways' => 'home#index'
  match 'targets/diseases' => 'home#index'

  match 'trees' => 'home#index'
  match 'trees/pharmacology' => 'home#index'

  match 'pathways' => 'home#index'
  match 'pathways/compounds' => 'home#index'

  match 'diseases' => 'home#index'
  match 'diseases/targets' => 'home#index'

  resources :search, :only => [ :index ] do
    collection do
      get 'typeahead'
    end
  end

  resources :core_api_calls, :except => [ :index, :show, :create, :new, :edit, :update, :destroy ] do
    collection do
      post :tab_separated_file
      get :tsv_download
      get :tsv_status
      get :organisms
      post :chemspider_tab_separated_file
    end
  end

  match '*path' => 'home#index'

end
get 'biopathway/index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
	  <meta name="viewport" content="width=device-width, initial-scale=1">      
    <%= stylesheet_link_tag :application, :media => :all %>
  <script type="text/javascript">
    var ldaBaseUrl = '<%= AppSettings.config["api"]["url"] -%>';
    var appID = '<%= AppSettings.config["keys"]["app_id"] -%>';
    var appKey = '<%= AppSettings.config["keys"]["app_key"] -%>';
    var tsvCreateUrl = '<%= tab_separated_file_core_api_calls_url -%>?';
    var tsvStatusUrl = '<%= tsv_status_core_api_calls_url -%>?';
    var tsvDownloadUrl = '<%= tsv_download_core_api_calls_url -%>?';
    var typeaheadUrl = '<%= typeahead_search_index_url -%>';
    var organismsUrl = '<%= organisms_core_api_calls_url -%>?';
    var cs_download_url = '<%= chemspider_tab_separated_file_core_api_calls_url -%>';
    var closedForMaintenance = '<%= AppSettings.config["maintenance"] -%>';

    // asset_path and root_url are the same but in theory could be different if it wasn't for some bootstrap glyphicon issues
    // both are picked up from the same app_settings var. root url is used by the ember router to set the base url for the js side
    // so that the urls are configured correctly by the router. The asset_path is used for image loading, see the 'getImage'
    // handlebars helper.
   var asset_path = '<%= Rails.application.config.relative_url_root != nil ? Rails.application.config.relative_url_root + "/assets": "/assets" -%>'; 
    var root_url = '<%= Rails.application.config.relative_url_root != nil ? Rails.application.config.relative_url_root: "/" -%>';
  </script>

    <script type="text/javascript">
      var frag_id = window.location.hash;
      if (frag_id !== null && frag_id !== "") {
        var rloc = window.location.protocol + "//" + window.location.hostname + ':' + window.location.port + window.location.pathname + '?' + location.hash.substr(2,frag_id.length);
        window.location = rloc; 
      }
    </script>
    <%= javascript_include_tag :application %>
    <script type="text/javascript">
        jQuery.support.cors = true;
    </script>

  <!-- Load browser polyfills for missing features, see https://github.com/Financial-Times/polyfill-service -->
  <script src="https://cdn.polyfill.io/v1/polyfill.min.js"></script>
    <title>Open PHACTS Explorer</title>
  <%= csrf_meta_tags %>
  <!-- <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery-ajaxtransport-xdomainrequest/1.0.1/jquery.xdomainrequest.min.js'></script> -->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
<script type="text/javascript">var oldIE = false;</script>
<!--[if lte IE 9]>
    
    <script type="text/javascript">
        oldIE = true;
    </script>

    <![endif]-->
    <%= yield %>
  </body>
</html>

app/views/layouts/biosearch.html.erb
<!DOCTYPE html>
<head>
	<title>BioSearch Pathway</title>
	<%= javascript_include_tag 'combined','d3sparql'  ,'data-no-turbolink' => true %>
</head>
<body>
	<%= yield %>
</body>

</html>